import React from "react";
import { FiArrowRight, FiBriefcase, FiFilter, FiPlus, FiSearch, FiX } from "react-icons/fi";
import MobileJobCard from "../ui/MobileJobCard";
import ExportButton from "../common/ExportButton";

const statuses = ["all", "posted", "in progress", "completed"];
const statusBadge = (status) => { const value = (status || "").toLowerCase(); if (value.includes("escrow")) return "bg-sky-50 text-[#016EA6]"; if (value.includes("progress") || value === "active") return "bg-orange-50 text-orange-500"; if (value.includes("complete")) return "bg-green-50 text-green-600"; return "bg-amber-50 text-amber-700"; };
const actionStyle = (action) => action === "Fund Escrow" ? "bg-[#016EA6] hover:bg-[#061EA6] text-white" : action === "Release Funds" ? "bg-emerald-600 hover:bg-emerald-700 text-white" : "bg-sky-50 hover:bg-[#016EA6]/10 text-[#016EA6]";

const SearchInput = ({ value, onChange, placeholder }) => <div className="relative min-w-0 flex-1"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-3.5 h-3.5" /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="w-full rounded-full border border-gray-100 bg-gray-50 py-2 pl-8 pr-7 text-xs font-medium text-gray-800 outline-none transition-all focus:border-[#016EA6] focus:bg-white" />{value && <button onClick={() => onChange("")} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400"><FiX className="w-3 h-3" /></button>}</div>;
const EmptyJobs = ({ search, statusFilter, onPost }) => <div className="py-12 px-4 rounded-2xl bg-gradient-to-b from-gray-50/60 to-white border border-dashed border-gray-200 flex flex-col items-center justify-center text-center"><FiBriefcase className="w-8 h-8 text-[#016EA6] mb-3" /><h4 className="text-sm font-bold text-gray-900 mb-1">No Active Jobs Found</h4><p className="text-xs text-gray-400 font-medium max-w-sm mb-5 leading-relaxed">{search || statusFilter !== "all" ? "No active jobs match your search keywords or filter criteria." : "You currently have no active project contracts. Post a new job or explore verified professionals."}</p><button onClick={onPost} className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#016EA6] text-white rounded-full text-xs font-bold"><span>Post a new job</span><FiArrowRight className="w-3.5 h-3.5" /></button></div>;

const DesktopTable = ({ jobs, onViewProject, search, statusFilter, onPost, isLoading }) => { if (isLoading) return <p className="py-12 text-center text-xs text-gray-400">Loading jobs...</p>; if (!jobs.length) return <EmptyJobs search={search} statusFilter={statusFilter} onPost={onPost} />; return <table className="w-full min-w-[760px] table-fixed border-collapse text-left text-xs"><thead><tr className="border-b border-gray-50 text-gray-400"><th className="w-[26%] pb-3 pr-4">Order ID</th><th className="w-[27%] pb-3 pr-4">Job title</th><th className="w-[18%] pb-3 pr-4">Professional</th><th className="w-[14%] pb-3 pr-4">Status</th><th className="w-[15%] pb-3">Action</th></tr></thead><tbody className="divide-y divide-gray-50">{jobs.map((job) => <tr key={job.id}><td className="py-4 pr-4 font-semibold text-gray-500">{job.id}</td><td className="py-4 pr-4 font-bold text-gray-800">{job.title}</td><td className="py-4 pr-4 font-semibold text-gray-800">{job.professional}</td><td className="py-4 pr-4"><span className={`px-2.5 py-1 rounded-lg font-bold text-[10px] ${statusBadge(job.status)}`}>{job.status}</span></td><td className="py-4"><button onClick={() => onViewProject(job.id)} className={`px-3 py-1.5 rounded-full text-xs font-bold ${actionStyle(job.actionText)}`}>{job.actionText}</button></td></tr>)}</tbody></table>; };

const EmployerActiveJobs = ({ jobs, search, setSearch, statusFilter, setStatusFilter, showFilterMenu, setShowFilterMenu, onViewProject, onPost, onExport, isLoading }) => <><div className="md:hidden bg-white border border-gray-100 rounded-3xl p-5 space-y-4"><div className="flex items-center justify-between gap-2"><h3 className="text-base font-bold text-gray-900">Active jobs {jobs.length > 0 && <span className="ml-2 px-2 py-0.5 rounded-full text-[10px] bg-sky-50 text-[#016EA6]">{jobs.length}</span>}</h3><SearchInput value={search} onChange={setSearch} placeholder="Search jobs..." /></div>{jobs.length ? <div className="space-y-3">{jobs.map((job) => <MobileJobCard key={job.id} job={job} onViewDetails={() => onViewProject(job.id)} />)}</div> : <p className="py-8 text-center text-xs text-gray-400">No active jobs found</p>}</div><div className="hidden md:block rounded-3xl border border-gray-100 bg-white p-6 lg:p-8"><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><h3 className="text-base font-bold text-gray-900">Active jobs <span className="ml-2 rounded-full bg-sky-50 px-2 py-0.5 text-[10px] text-[#016EA6]">{jobs.length}</span></h3><div className="flex items-center gap-2"><SearchInput value={search} onChange={setSearch} placeholder="Search active jobs..." /><div className="relative"><button onClick={() => setShowFilterMenu(!showFilterMenu)} className="flex items-center gap-1.5 rounded-full border border-gray-100 px-3 py-2 text-xs font-semibold text-gray-500"><FiFilter className="w-3.5 h-3.5" />{statusFilter === "all" ? "Filter" : statusFilter}</button>{showFilterMenu && <div className="absolute right-0 mt-2 w-44 bg-white border border-gray-100 rounded-2xl shadow-lg py-1.5 z-30">{statuses.map((status) => <button key={status} onClick={() => { setStatusFilter(status); setShowFilterMenu(false); }} className="w-full text-left px-3.5 py-1.5 text-xs capitalize hover:bg-gray-50">{status === "all" ? "All Statuses" : status}</button>)}</div>}</div><ExportButton onExport={onExport} disabled={!jobs.length} /><button onClick={onPost} className="flex items-center gap-1.5 rounded-full bg-[#016EA6] px-4 py-2 text-xs font-bold text-white"><FiPlus className="w-3.5 h-3.5" />Post a new job</button></div></div><div className="overflow-x-auto"><DesktopTable jobs={jobs} onViewProject={onViewProject} search={search} statusFilter={statusFilter} onPost={onPost} isLoading={isLoading} /></div></div></>;

export default EmployerActiveJobs;